### ISSUE TITLE
Phitron

### ISSUE THREAD

**Issue by jihad-islam** [phitronio/Batch-4-Introduction-to-C-Programming#1]

**Comment by abutalha011** [comment]
[image: image.png]



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/08/23,
06:23:37 PM
